"""GitHub API repo activity (works keyless, rate-limited) + Electric Capital
crypto-ecosystems mapping (TODO). PLAN.md §2 #5.

GitHub's REST API works unauthenticated at 60 req/hour; set GITHUB_TOKEN to
raise that to 5000/hour — verified live 2026-07-02 without a token.

Electric Capital's `crypto-ecosystems` repo does NOT ship pre-built export
files in the repo tree (checked 2026-07-02 — no exports/ dir at HEAD); their
ecosystem-to-repo mapping is generated by running the repo's own Python
toolkit (`run.sh`) locally against its TOML ecosystem definitions. That's
real engineering work (clone repo, run their export pipeline, parse
output), not an API call — deferred; this collector only does the GitHub
half until that's built.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Iterable

import requests

from quiverquant.collectors.base import Collector
from quiverquant.config import get_source

GITHUB_API = "https://api.github.com"

# Placeholder watchlist — repos to track dev activity for. Should eventually
# be sourced from the Electric Capital ecosystem mapping once that's built,
# rather than hardcoded.
DEFAULT_REPOS = [
    "ethereum/go-ethereum",
    "bitcoin/bitcoin",
    "solana-labs/solana",
    "paradigmxyz/reth",
]


class DevActivityCollector(Collector):
    name = "github"

    def __init__(self, repos: list[str] | None = None):
        self.repos = repos or DEFAULT_REPOS

    def fetch(self, tier: str) -> Iterable[dict[str, Any]]:
        token = get_source(self.name).active_key()
        headers = {"Authorization": f"Bearer {token}"} if token else {}
        now = datetime.now(timezone.utc)
        for repo in self.repos:
            resp = requests.get(f"{GITHUB_API}/repos/{repo}", headers=headers, timeout=30)
            if resp.status_code != 200:
                continue
            d = resp.json()
            yield {
                "signal_type": "repo_activity",
                "entity": repo,
                "ts": now,
                "payload": {
                    "stars": d.get("stargazers_count"),
                    "forks": d.get("forks_count"),
                    "open_issues": d.get("open_issues_count"),
                    "watchers": d.get("subscribers_count"),
                    "pushed_at": d.get("pushed_at"),
                },
            }
